name: tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Run tests
      run: cargo test

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Format code
      run: cargo fmt -- --check
